In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/'

In [4]:
dframe_wine = pd.read_csv('winequality-red.csv',sep=';')

In [5]:
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [9]:
dframe_wine['alcohol'].mean()

10.422983114446502

In [10]:
def max_to_min(arr):
    return arr.max() - arr.min()

In [11]:
wino = dframe_wine.groupby('quality')

In [16]:
wino.describe().stack()

               fixed acidity  volatile acidity  citric acid  residual sugar  \
quality
3       count      10.000000         10.000000    10.000000       10.000000
        mean        8.360000          0.884500     0.171000        2.635000
        std         1.770875          0.331256     0.250664        1.401596
        min         6.700000          0.440000     0.000000        1.200000
        25%         7.150000          0.647500     0.005000        1.875000
        50%         7.500000          0.845000     0.035000        2.100000
        75%         9.875000          1.010000     0.327500        3.100000
        max        11.600000          1.580000     0.660000        5.700000
4       count      53.000000         53.000000    53.000000       53.000000
        mean        7.779245          0.693962     0.174151        2.694340
        std         1.626624          0.220110     0.201030        1.789436
        min         4.600000          0.230000     0.000000        1.300000
        25%         6.800000          0.530000     0.030000        1.900000
        50%         7.500000          0.670000     0.090000        2.100000
        75%         8.400000          0.870000     0.270000        2.800000
        max        12.500000          1.130000     1.000000       12.900000
5       count     681.000000        681.000000   681.000000      681.000000
        mean        8.167254          0.577041     0.243686        2.528855
        std         1.563988          0.164801     0.180003        1.359753
        min         5.000000          0.180000     0.000000        1.200000
        25%         7.100000          0.460000     0.090000        1.900000
        50%         7.800000          0.580000     0.230000        2.200000
        75%         8.900000          0.670000     0.360000        2.600000
        max        15.900000          1.330000     0.790000       15.500000
6       count     638.000000        638.000000   638.000000      638.000000
        mean        8.347179          0.497484     0.273824        2.477194
        std         1.797849          0.160962     0.195108        1.441576
        min         4.700000          0.160000     0.000000        0.900000
        25%         7.000000          0.380000     0.090000        1.900000
        50%         7.900000          0.490000     0.260000        2.200000
        75%         9.400000          0.600000     0.430000        2.500000
        max        14.300000          1.040000     0.780000       15.400000
7       count     199.000000        199.000000   199.000000      199.000000
        mean        8.872362          0.403920     0.375176        2.720603
        std         1.992483          0.145224     0.194432        1.371509
        min         4.900000          0.120000     0.000000        1.200000
        25%         7.400000          0.300000     0.305000        2.000000
        50%         8.800000          0.370000     0.400000        2.300000
        75%        10.100000          0.485000     0.490000        2.750000
        max        15.600000          0.915000     0.760000        8.900000
8       count      18.000000         18.000000    18.000000       18.000000
        mean        8.566667          0.423333     0.391111        2.577778
        std         2.119656          0.144914     0.199526        1.295038
        min         5.000000          0.260000     0.030000        1.400000
        25%         7.250000          0.335000     0.302500        1.800000
        50%         8.250000          0.370000     0.420000        2.100000
        75%        10.225000          0.472500     0.530000        2.600000
        max        12.600000          0.850000     0.720000        6.400000

                chlorides  free sulfur dioxide  total sulfur dioxide  \
quality
3       count   10.000000            10.000000             10.000000
        mean     0.122500            11.000000             24.900000
        std      0.066241             9.763879             16.828877
        min      0.061000             3.000000              9.000000
        25%      0.079000             5.000000             12.500000
        50%      0.090500             6.000000             15.000000
        75%      0.143000            14.500000             42.500000
        max      0.267000            34.000000             49.000000
4       count   53.000000            53.000000             53.000000
        mean     0.090679            12.264151             36.245283
        std      0.076192             9.025926             27.583374
        min      0.045000             3.000000              7.000000
        25%      0.067000             6.000000             14.000000
        50%      0.080000            11.000000             26.000000
        75%      0.089000            15.000000             49.000000
        max      0.610000            41.000000            119.000000
5       count  681.000000           681.000000            681.000000
        mean     0.092736            16.983847             56.513950
        std      0.053707            10.955446             36.993116
        min      0.039000             3.000000              6.000000
        25%      0.074000             9.000000             26.000000
        50%      0.081000            15.000000             47.000000
        75%      0.094000            23.000000             84.000000
        max      0.611000            68.000000            155.000000
6       count  638.000000           638.000000            638.000000
        mean     0.084956            15.711599             40.869906
        std      0.039563             9.940911             25.038250
        min      0.034000             1.000000              6.000000
        25%      0.068250             8.000000             23.000000
        50%      0.078000            14.000000             35.000000
        75%      0.088000            21.000000             54.000000
        max      0.415000            72.000000            165.000000
7       count  199.000000           199.000000            199.000000
        mean     0.076588            14.045226             35.020101
        std      0.029456            10.175255             33.191206
        min      0.012000             3.000000              7.000000
        25%      0.062000             6.000000             17.500000
        50%      0.073000            11.000000             27.000000
        75%      0.087000            18.000000             43.000000
        max      0.358000            54.000000            289.000000
8       count   18.000000            18.000000             18.000000
        mean     0.068444            13.277778             33.444444
        std      0.011678            11.155613             25.433240
        min      0.044000             3.000000             12.000000
        25%      0.062000             6.000000             16.000000
        50%      0.070500             7.500000             21.500000
        75%      0.075500            16.500000             43.000000
        max      0.086000            42.000000             88.000000

                  density          pH   sulphates     alcohol
quality
3       count   10.000000   10.000000   10.000000   10.000000
        mean     0.997464    3.398000    0.570000    9.955000
        std      0.002002    0.144052    0.122020    0.818009
        min      0.994710    3.160000    0.400000    8.400000
        25%      0.996150    3.312500    0.512500    9.725000
        50%      0.997565    3.390000    0.545000    9.925000
        75%      0.998770    3.495000    0.615000   10.575000
        max      1.000800    3.630000    0.860000   11.000000
4       count   53.000000   53.000000   53.000000   53.000000
        mean     0.996542    3.381509    0.596415   10.265094
        std      0.001575    0.181441    0.239391    0.934776
        min      0.993400    2.740000    0.330000    9.000000
        25%      0.995650    3.300000    0.490000    9.600000
        50%      0.996500    3.370000    0.560000   10.000000
        75%      0.997450    3.500000    0.600000   11.000000
        max      1.001000    3.900000    2.000000   13.100000
5       count  681.000000  681.000000  681.000000  681.000000
        mean     0.997104    3.304949    0.620969    9.899706
        std      0.001589    0.150618    0.171062    0.736521
        min      0.992560    2.880000    0.370000    8.500000
        25%      0.996200    3.200000    0.530000    9.400000
        50%      0.997000    3.300000    0.580000    9.700000
        75%      0.997900    3.400000    0.660000   10.200000
        max      1.003150    3.740000    1.980000   14.900000
6       count  638.000000  638.000000  638.000000  638.000000
        mean     0.996615    3.318072    0.675329   10.629519
        std      0.002000    0.153995    0.158650    1.049639
        min      0.990070    2.860000    0.400000    8.400000
        25%      0.995402    3.220000    0.580000    9.800000
        50%      0.996560    3.320000    0.640000   10.500000
        75%      0.997893    3.410000    0.750000   11.300000
        max      1.003690    4.010000    1.950000   14.000000
7       count  199.000000  199.000000  199.000000  199.000000
        mean     0.996104    3.290754    0.741256   11.465913
        std      0.002176    0.150101    0.135639    0.961933
        min      0.990640    2.920000    0.390000    9.200000
        25%      0.994765    3.200000    0.650000   10.800000
        50%      0.995770    3.280000    0.740000   11.500000
        75%      0.997360    3.380000    0.830000   12.100000
        max      1.003200    3.780000    1.360000   14.000000
8       count   18.000000   18.000000   18.000000   18.000000
        mean     0.995212    3.267222    0.767778   12.094444
        std      0.002378    0.200640    0.115379    1.224011
        min      0.990800    2.880000    0.630000    9.800000
        25%      0.994175    3.162500    0.690000   11.325000
        50%      0.994940    3.230000    0.740000   12.150000
        75%      0.997200    3.350000    0.820000   12.875000
        max      0.998800    3.720000    1.100000   14.000000

In [13]:
wino.agg(max_to_min)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,4.9,1.140,0.66,4.5,0.206,31.0,40.0,0.00609,0.47,0.46,2.6
4,7.9,0.900,1.00,11.6,0.565,38.0,112.0,0.00760,1.16,1.67,4.1
5,10.9,1.150,0.79,14.3,0.572,65.0,149.0,0.01059,0.86,1.61,6.4
6,9.6,0.880,0.78,14.5,0.381,71.0,159.0,0.01362,1.15,1.55,5.6
7,10.7,0.795,0.76,7.7,0.346,51.0,282.0,0.01256,0.86,0.97,4.8
8,7.6,0.590,0.69,5.0,0.042,39.0,76.0,0.00800,0.84,0.47,4.2

In [17]:
dframe_wine['qual/alc ratio'] = dframe_wine['quality'] / dframe_wine['alcohol']

In [19]:
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,qual/alc ratio
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0.531915
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0.510204
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0.510204
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0.612245
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0.531915

In [20]:
dframe_wine.pivot_table(index=['quality'])

,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,qual/alc ratio,residual sugar,sulphates,total sulfur dioxide,volatile acidity
quality,,,,,,,,,,,,
3,9.955000,0.122500,0.171000,0.997464,8.360000,11.000000,3.398000,0.303286,2.635000,0.570000,24.900000,0.884500
4,10.265094,0.090679,0.174151,0.996542,7.779245,12.264151,3.381509,0.392724,2.694340,0.596415,36.245283,0.693962
5,9.899706,0.092736,0.243686,0.997104,8.167254,16.983847,3.304949,0.507573,2.528855,0.620969,56.513950,0.577041
6,10.629519,0.084956,0.273824,0.996615,8.347179,15.711599,3.318072,0.569801,2.477194,0.675329,40.869906,0.497484
7,11.465913,0.076588,0.375176,0.996104,8.872362,14.045226,3.290754,0.614855,2.720603,0.741256,35.020101,0.403920
8,12.094444,0.068444,0.391111,0.995212,8.566667,13.277778,3.267222,0.668146,2.577778,0.767778,33.444444,0.423333